analytics:
  lanes:
  - coords:
    - - 252
      - 351
    - - 442
      - 294
    - - 747
      - 575
    - - 404
      - 661
    id: 1
    name: Lane 1
  - coords:
    - - 605
      - 252
    - - 753
      - 183
    - - 1089
      - 316
    - - 906
      - 445
    id: 2
    name: Lane 2
  queue_threshold_speed: 2
  speed_limit_pixels: 25
  stop_line_coords:
  - - 345
    - 611
  - - 1267
    - 626
detection:
  classes:
  - 2
  - 3
  - 5
  - 7
  model: yolo11m.pt
tracking:
  max_disappeared: 50
  max_distance: 150
video:
  fps: 30
  output: output/processed_video.mp4
  resize_height: 720
  resize_width: 1280
  source: data/sample_video.mp4
